doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 120
autodetect: true
requirements:
  - pyRestTable
  - PyGitHub>=1.32
  - PyQt
  - numpy
  - h5py
  - lxml
  - requests
  - coverage
  - docopt
  - coveralls
ignore-paths:
  - docs
  - src/punx/cache
  - src/punx/data
  - src/punx/ignore_now
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
  - ^versioneer\.py$
  - ^src/punx/_version\.py$
python-targets:
  - 2
  - 3
