doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 120
uses:
  - requests
  - coverage
  - docopt
  - coveralls
autodetect: true
requirements:
  - pyRestTable
  - PyGitHub>=1.32
  - PyQt
  - numpy
  - h5py
  - lxml
ignore-paths:
  - docs
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 2
  - 3
