sudo: false
language: python
python:
  - "2.7"

before_script:
  - wget http://repo.continuum.io/miniconda/Miniconda2-4.2.12-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda install --yes numpy h5py lxml requests pyqt=4
  - pip install pyRestTable
  - cd $HOME/build/prjemian/punx/src/punx
  - cd $HOME

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages

addons:
  apt:
    packages:
      - libhdf5-serial-dev

install:
  - cd $HOME/build/prjemian/punx
  - pip install -r requirements.txt
  - pip install .
  
# command to run tests
script:
  - punx -h
  - punx update --force
  - cd $HOME/build/prjemian/punx/src/qa_qc
  - for filename in test_*.py; do echo "==========  $filename ==========";python "$filename" -v; done
